=== Cr4ckX/wba2_ss13/Java Phase 1/Aufgabe3/Aufgabe3d_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Rezepte">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Rezept" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Rezeptname" type="xs:string"/>
                            <xs:element name="Zutaten">                               
                                <xs:complexType>    
                                    <xs:sequence>
                                        <xs:element name="Zutat" minOccurs="1" maxOccurs="unbounded">   
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Name" type="xs:string"/>
                                                    <xs:element name="Menge" type="noZero"/>
                                                    <xs:element name="Einheit" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Zubereitung">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Arbeitszeit">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Zeit" type="noZero"/>
                                                    <xs:element name="Einheit" type="xs:string"/> <!-- oder type="ArbeitszeitEinheit" -->
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Schwierigkeitsgrad" type="Schwierigkeit" default="normal"/>
                                        <xs:element name="Brennwert">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Personen" type="noZero" default="1"/>
                                                    <xs:element name="Anzahl" type="noZero"/>
                                                    <xs:element name="Einheit" type="xs:string" default="kcal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Beschreibung" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Kommentare">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Kommentar" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Nutzer" type="xs:string"/>
                                                    <xs:element name="Datum">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Tag" type="DatumTag"/>
                                                                <xs:element name="Monat" type="DatumMonat"/>
                                                                <xs:element name="Jahr" type="DatumJahr"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Uhrzeit">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Stunde" type="UhrStunde"/>
                                                                <xs:element name="Minute" type="UhrMinute"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Inhalt" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:integer" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Integer not 0  -->                                                 
    <xs:simpleType name="noZero">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
        </xs:restriction>    
    </xs:simpleType>
    
    <!-- Selbst definierter Datentyp - Beispiel, jedoch nicht fest implementiert-->
    
    <xs:simpleType name="ArbeitszeitEinheit">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Min."/>
            <xs:enumeration value="Std."/>
            <xs:enumeration value="Tag(e)"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <!-- Selbst definierter Datentyp - diesmal implementiert -->
    
    <xs:simpleType name="Schwierigkeit">
        <xs:restriction base="xs:string">
            <xs:enumeration value="leicht"/>
            <xs:enumeration value="normal"/>
            <xs:enumeration value="schwer"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Datentyp für Uhrzeit -->
    
    <xs:simpleType name="UhrStunde">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-1][0-9]|20|21|22|23"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="UhrMinute">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Datentyp für Datum -->
    
    <xs:simpleType name="DatumTag">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-2][1-9]|10|20|30|31"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="DatumMonat">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0][1-9]|10|11|12"/>
        </xs:restriction>
    </xs:simpleType>   
    
    <xs:simpleType name="DatumJahr">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[2][0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>   
</xs:schema>

=== Cr4ckX/wba2_ss13/Java Phase 1/Aufgabe3/Aufgabe3d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Hierbei handelt es sich um die XML-Datei, welche gegen das erstelle Schema geprÃ¼ft wird.-->
<Rezepte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Aufgabe3d_1.xsd">
    <Rezept id="1">
        <Rezeptname>Mein Lieblingsgericht</Rezeptname>
        <Zutaten>
            <Zutat>
                <Name>Mandeln</Name>
                <Menge>500</Menge>
                <Einheit>g</Einheit>
            </Zutat>
            <Zutat>
                <Name>Mehl</Name>
                <Menge>1</Menge>
                <Einheit>kg</Einheit>
            </Zutat>
        </Zutaten>
        <Zubereitung>
            <Arbeitszeit>
                <Zeit>3</Zeit>
                <Einheit>Std.</Einheit>
            </Arbeitszeit>
            <Schwierigkeitsgrad>schwer</Schwierigkeitsgrad>
            <Brennwert>
                <Personen>1</Personen>
                <Anzahl>3000</Anzahl>
                <Einheit>kcal</Einheit>
            </Brennwert>
            <Beschreibung>Alle Zutaten mischen. Fertig!</Beschreibung>
        </Zubereitung>
    </Rezept>
    
    <Rezept id="2">
        <Rezeptname>Mein zweites Lieblingsgericht</Rezeptname>
        <Zutaten>
            <Zutat>
                <Name>Eier</Name>
                <Menge>12</Menge>
                <Einheit>default</Einheit>
            </Zutat>
        </Zutaten>
        <Zubereitung>
            <Arbeitszeit>
                <Zeit>10</Zeit>
                <Einheit>Min.</Einheit>
            </Arbeitszeit>
            <Schwierigkeitsgrad>leicht</Schwierigkeitsgrad>
            <Brennwert>
                <Personen>2</Personen>
                <Anzahl>300</Anzahl>
                <Einheit>kcal</Einheit>
            </Brennwert>
            <Beschreibung>Eier bleiben wie sie sind.</Beschreibung>
        </Zubereitung>
    </Rezept>
</Rezepte>
